# Generated by Django 6.0.7 on 2026-07-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('backend', 'Backend'), ('mecatronique', 'Mécatronique'), ('cybersecurite', 'Cybersécurité'), ('autre', 'Autre')], max_length=20)),
                ('niveau', models.IntegerField(help_text='Pourcentage de 0 à 100')),
                ('icone', models.CharField(help_text='Ex: fab fa-python (FontAwesome)', max_length=50)),
                ('description_courte', models.CharField(max_length=150)),
                ('description_longue', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('type_experience', models.CharField(choices=[('formation', 'Formation'), ('projet', 'Projet'), ('experience', 'Expérience')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('en_cours', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description_courte', models.CharField(max_length=200)),
                ('description_longue', models.TextField()),
                ('technologies', models.CharField(help_text='Séparées par des virgules', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
                ('lien_github', models.URLField(blank=True)),
                ('lien_demo', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_creation', models.DateField()),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
